"""Emojis used throughout the app"""
GEM = ":gem:"
HEART_EYES = ":heart_eyes:"
CALENDAR = ":calendar:"
FACE_HOLDING_BACK_TEARS = ":face_holding_back_tears:"
HEART_HANDS = ":heart_hands:"
CURRENCY_EXCHANGE = ":currency_exchange:"
X = ":x:"
NUMBERS = ":1234:"
MAN_SHRUGGING = ":man_shrugging:"
CRY = ":cry:"
HEART = ":heart:"
PLEADING_FACE = ":pleading_face:"
STAR_STRUCK = ":star_struck:"
