name: 'Quality Check'

on:
  push

permissions:
  contents: read

defaults:
  run:
    shell: bash
    
concurrency:
  group: ${{ github.ref }}

env:
  RUNNER_IMAGE_NAME: github-runner-image

jobs:

  check-code:
    name: Check Code
    runs-on: ubuntu-22.04
    environment: production

    steps:
    - name: Checkout Branch
      uses: actions/checkout@v3

    - name: Build Runner Image
      run: make build-runner-image

    - name: Run Terraform Lint
      run: make run-command-in-container-lint-terraform

    - name: Run Tests
      run: make run-command-in-container-run-tests
